import { createHash } from "node:crypto";

/**
 * The maze, and the reason it costs money to be in one.
 *
 * A demo where an agent buys things proves that it *can* pay. It does not show the thing that
 * matters, which is an agent deciding **whether** to. So the maze is priced to make that decision
 * real: moving is cheap, looking is dearer, and the map costs about as much as a dozen steps. An
 * agent that buys the map immediately overpays on a short path and saves a fortune on a long one,
 * and it cannot know which it has without spending something to find out.
 *
 * That is the point. The allowance is not a formality the agent spends down — it is the constraint
 * it has to think inside.
 *
 * The maze is a **perfect maze**: exactly one path between any two cells, no loops, no islands.
 * Generated by depth-first search from a seed, so the same round id always produces the same maze
 * and a run can be replayed by anyone holding the id. Nothing about the layout is secret; what
 * costs money is *seeing* it.
 */

export const WIDTH = 6;
export const HEIGHT = 6;

/** The four directions, named once. `Direction` is derived so the two can never disagree. */
export const DIRECTION_NAMES = ["n", "s", "e", "w"] as const;
export type Direction = (typeof DIRECTION_NAMES)[number];

/** A cell's open sides, as a bitmask. A cell knows its own exits without a lookup elsewhere. */
export type Cell = number;
export type Maze = readonly Cell[];

export interface Point {
  readonly x: number;
  readonly y: number;
}

const N = 1, S = 2, E = 4, W = 8;

const OPPOSITE: Readonly<Record<number, number>> = { [N]: S, [S]: N, [E]: W, [W]: E };
const STEP: Readonly<Record<number, readonly [number, number]>> = {
  [N]: [0, -1], [S]: [0, 1], [E]: [1, 0], [W]: [-1, 0],
};

export const DIRECTIONS: Readonly<Record<Direction, number>> = { n: N, s: S, e: E, w: W };


export const isDirection = (value: unknown): value is Direction =>
  typeof value === "string" && Object.hasOwn(DIRECTIONS, value);

/**
 * A small deterministic generator, seeded from the round id.
 *
 * `Math.random` would make a maze nobody can check. Seeding from the id means a run is reproducible
 * from public information, which is what lets a spectator verify an agent actually solved the maze
 * rather than being handed the exit.
 */
function seededRandom(seed: string): () => number {
  const digest = createHash("sha256").update(seed).digest();
  let a = digest.readUInt32LE(0) || 1;
  let b = digest.readUInt32LE(4) || 2;
  let c = digest.readUInt32LE(8) || 3;
  let d = digest.readUInt32LE(12) || 4;
  return () => {
    const t = a ^ (a << 11);
    a = b; b = c; c = d;
    d = (d ^ (d >>> 19) ^ (t ^ (t >>> 8))) >>> 0;
    return d / 0x1_0000_0000;
  };
}

const index = (x: number, y: number): number => y * WIDTH + x;

/** The same index, for callers holding a Point. Cells are addressed this way in `Known`. */
export const indexOf = (p: Point): number => index(p.x, p.y);
const inside = (x: number, y: number): boolean => x >= 0 && y >= 0 && x < WIDTH && y < HEIGHT;

/** `noUncheckedIndexedAccess` is on, and every read here is provably in range. */
const at = (cells: Maze, x: number, y: number): Cell => cells[index(x, y)] ?? 0;

export const START: Point = { x: 0, y: 0 };
export const EXIT: Point = { x: WIDTH - 1, y: HEIGHT - 1 };

/**
 * Carve a perfect maze by depth-first search.
 *
 * Every cell starts walled in; the walk knocks out exactly one wall per cell it reaches, so the
 * result is a spanning tree — connected, and with no cycles. That guarantees the exit is always
 * reachable, which matters when somebody is paying by the step to look for it.
 */
export function generate(seed: string): Maze {
  const cells = new Array<Cell>(WIDTH * HEIGHT).fill(0);
  const seen = new Array<boolean>(WIDTH * HEIGHT).fill(false);
  const random = seededRandom(seed);
  const stack: Point[] = [START];
  seen[0] = true;

  while (stack.length > 0) {
    const here = stack[stack.length - 1]!;
    const options = [N, S, E, W].filter((bit) => {
      const [dx, dy] = STEP[bit]!;
      return inside(here.x + dx, here.y + dy) && !seen[index(here.x + dx, here.y + dy)];
    });
    if (options.length === 0) {
      stack.pop();
      continue;
    }
    const bit = options[Math.floor(random() * options.length)]!;
    const [dx, dy] = STEP[bit]!;
    cells[index(here.x, here.y)] = at(cells, here.x, here.y) | bit;
    cells[index(here.x + dx, here.y + dy)] = at(cells, here.x + dx, here.y + dy) | OPPOSITE[bit]!;
    seen[index(here.x + dx, here.y + dy)] = true;
    stack.push({ x: here.x + dx, y: here.y + dy });
  }
  return cells;
}

export function exits(cells: Maze, x: number, y: number): readonly Direction[] {
  const open = at(cells, x, y);
  return DIRECTION_NAMES.filter((name) => (open & DIRECTIONS[name]) !== 0);
}

export const canMove = (cells: Maze, x: number, y: number, direction: Direction): boolean =>
  (at(cells, x, y) & DIRECTIONS[direction]) !== 0;

export function moved(x: number, y: number, direction: Direction): Point {
  const [dx, dy] = STEP[DIRECTIONS[direction]]!;
  return { x: x + dx, y: y + dy };
}

export const atExit = (x: number, y: number): boolean => x === EXIT.x && y === EXIT.y;

/**
 * The shortest route from a cell to the exit.
 *
 * Used for two honest purposes and no dishonest one: pricing the map against what it saves, and
 * telling a finished run how close to optimal it was. It is never served by an endpoint that has
 * not been paid for.
 *
 * Returns `null` only if the exit is unreachable, which a perfect maze makes impossible — the type
 * carries the possibility so a caller cannot silently assume otherwise.
 */
export function shortestPath(cells: Maze, from: Point = START): readonly Direction[] | null {
  const key = (p: Point): string => `${p.x},${p.y}`;
  const previous = new Map<string, { from: Point; direction: Direction }>();
  const queue: Point[] = [from];
  const visited = new Set<string>([key(from)]);

  while (queue.length > 0) {
    const here = queue.shift()!;
    if (atExit(here.x, here.y)) break;
    for (const direction of exits(cells, here.x, here.y)) {
      const next = moved(here.x, here.y, direction);
      if (visited.has(key(next))) continue;
      visited.add(key(next));
      previous.set(key(next), { from: here, direction });
      queue.push(next);
    }
  }

  const route: Direction[] = [];
  let cursor: Point = EXIT;
  while (key(cursor) !== key(from)) {
    const step = previous.get(key(cursor));
    if (!step) return null;
    route.unshift(step.direction);
    cursor = step.from;
  }
  return route;
}

/**
 * The maze as a machine reads it: every cell, and which way you may leave it.
 *
 * The drawing below is for people. An agent that has just paid for the map wants to plan a route,
 * and handing it ASCII art to parse would be selling it a picture of the thing it asked for. Both
 * come back from the same purchase — the buyer here is usually a machine, occasionally a person
 * watching one, and the price is for the knowledge rather than the format.
 */
export const openings = (cells: Maze): readonly (readonly (readonly Direction[])[])[] =>
  Array.from({ length: HEIGHT }, (_, y) =>
    Array.from({ length: WIDTH }, (_, x) => exits(cells, x, y)));

/**
 * What one run has established about the maze.
 *
 * Knowledge is per **wall**, not per cell, because that is what an agent actually buys. Walking
 * north proves the wall between two cells is open; walking into it proves it is shut; a look
 * settles every wall of the cell you are standing in. Recording it per cell would claim the agent
 * knows three sides it never tested.
 *
 * A wall is shared, so learning it from one side learns it from the other — otherwise the drawing
 * shows a passage from above and a mystery from below, which is the same wall twice.
 */
export interface Known {
  /** Per cell, a bitmask of the directions whose state has been settled. */
  readonly walls: readonly number[];
  /** Cells the run has actually stood in. */
  readonly visited: ReadonlySet<number>;
}

export const nothingKnown = (): Known =>
  ({ walls: new Array<number>(WIDTH * HEIGHT).fill(0), visited: new Set([index(START.x, START.y)]) });

export const everythingKnown = (): Known => ({
  walls: new Array<number>(WIDTH * HEIGHT).fill(N | S | E | W),
  visited: new Set([index(START.x, START.y)]),
});

/** Settle one wall, from both sides. */
export function learn(known: Known, x: number, y: number, direction: Direction): Known {
  const walls = [...known.walls];
  const bit = DIRECTIONS[direction];
  walls[index(x, y)] = (walls[index(x, y)] ?? 0) | bit;

  // A wall is shared, so learning it from one side learns it from the other. OPPOSITE already
  // maps a wall bit to the neighbour's matching bit — the same map the generator carves with.
  const next = moved(x, y, direction);
  if (inside(next.x, next.y)) {
    walls[index(next.x, next.y)] = (walls[index(next.x, next.y)] ?? 0) | (OPPOSITE[bit] ?? 0);
  }
  return { walls, visited: known.visited };
}

const settled = (known: Known, x: number, y: number, direction: Direction): boolean =>
  ((known.walls[index(x, y)] ?? 0) & DIRECTIONS[direction]) !== 0;

/**
 * The maze drawn for a person rather than a machine.
 *
 * The map endpoint sells this, and it is what a spectator sees at the end of a run — which is why
 * it marks where the agent is. A maze without the agent in it is a picture, not a story.
 */
/**
 * The maze as one run has bought it, rather than as it is.
 *
 * Three states per wall, not two, and the third is the point: **solid** is a wall this run proved
 * is there, **open** is a passage it proved is open, and **dotted** is a wall nobody has paid to
 * find out about. Drawing an untested wall as either one would be inventing a fact — and an agent
 * that has spent nothing would appear to know the whole maze.
 *
 * The lattice and the outer border stay solid throughout so the shape still reads as a maze. The
 * exit is drawn because its position is public: it is a constant, not something anybody buys.
 *
 * This hides nothing that is secret. The maze is derived from the round id and anybody can
 * recompute it. What this shows is what *this run* established, which is the interesting half —
 * watching an agent feel its way through, paying per fact.
 */
export function renderKnown(cells: Maze, known: Known, agent?: Point): string {
  const wall = (x: number, y: number, d: Direction, solid: string, gap: string, fog: string): string => {
    if (!settled(known, x, y, d)) return fog;
    return canMove(cells, x, y, d) ? gap : solid;
  };

  const lines: string[] = ["┌" + "───┬".repeat(WIDTH - 1) + "───┐"];
  for (let y = 0; y < HEIGHT; y++) {
    let middle = "│";
    let below = y === HEIGHT - 1 ? "└" : "├";
    for (let x = 0; x < WIDTH; x++) {
      const here = agent?.x === x && agent?.y === y;
      const seen = known.visited.has(index(x, y));
      middle += here ? " ◆ " : atExit(x, y) ? " ★ " : seen ? " · " : "   ";
      // The outer edge is never in doubt; only interior walls can be unknown.
      middle += x === WIDTH - 1 ? "│" : wall(x, y, "e", "│", " ", "┆");
      if (y === HEIGHT - 1) {
        below += "───" + (x === WIDTH - 1 ? "┘" : "┴");
      } else {
        below += wall(x, y, "s", "───", "   ", "┈┈┈");
        below += x === WIDTH - 1 ? "┤" : "┼";
      }
    }
    lines.push(middle, below);
  }
  return lines.join("\n");
}

export function render(cells: Maze, agent?: Point): string {
  const lines: string[] = ["┌" + "───┬".repeat(WIDTH - 1) + "───┐"];
  for (let y = 0; y < HEIGHT; y++) {
    let middle = "│";
    let below = y === HEIGHT - 1 ? "└" : "├";
    for (let x = 0; x < WIDTH; x++) {
      const here = agent?.x === x && agent?.y === y;
      middle += here ? " ◆ " : atExit(x, y) ? " ★ " : "   ";
      middle += (at(cells, x, y) & E) !== 0 ? " " : "│";
      if (y === HEIGHT - 1) {
        below += "───" + (x === WIDTH - 1 ? "┘" : "┴");
      } else {
        below += (at(cells, x, y) & S) !== 0 ? "   " : "───";
        below += x === WIDTH - 1 ? "┤" : "┼";
      }
    }
    lines.push(middle, below);
  }
  return lines.join("\n");
}
