import { createHash } from "node:crypto";

/**
 * The maze, and the reason it costs money to be in one.
 *
 * A demo where an agent buys things proves that it *can* pay. It does not show the thing that
 * matters, which is an agent deciding **whether** to. So the maze is priced to make that decision
 * real: moving is cheap, looking is dearer, and the map costs about as much as a dozen steps. An
 * agent that buys the map immediately overpays on a short path and saves a fortune on a long one,
 * and it cannot know which it has without spending something to find out.
 *
 * That is the whole point. The allowance is not a formality the agent spends down — it is the
 * constraint it has to think inside.
 *
 * The maze is a **perfect maze**: exactly one path between any two cells, no loops, no islands.
 * Generated by depth-first search from a seed, so the same game id always produces the same maze
 * and a run can be replayed by anyone who has the id. Nothing about the layout is secret; what
 * costs money is *seeing* it.
 */

export const WIDTH = 6;
export const HEIGHT = 6;

/** Walls are held per cell as a bitmask, so a cell knows its own exits without a lookup. */
const N = 1, S = 2, E = 4, W = 8;
const OPPOSITE = { [N]: S, [S]: N, [E]: W, [W]: E };
const STEP = { [N]: [0, -1], [S]: [0, 1], [E]: [1, 0], [W]: [-1, 0] };

export const DIRECTIONS = { n: N, s: S, e: E, w: W };

/**
 * A small deterministic generator, seeded from the game id.
 *
 * `Math.random` would make a maze nobody can check. Seeding from the id means a run is
 * reproducible from public information, which is what lets a spectator verify that the agent
 * actually solved it rather than being handed the exit.
 */
function seededRandom(seed) {
  const digest = createHash("sha256").update(seed).digest();
  let a = digest.readUInt32LE(0) || 1;
  let b = digest.readUInt32LE(4) || 2;
  let c = digest.readUInt32LE(8) || 3;
  let d = digest.readUInt32LE(12) || 4;
  return () => {
    const t = a ^ (a << 11);
    a = b; b = c; c = d;
    d = (d ^ (d >>> 19) ^ (t ^ (t >>> 8))) >>> 0;
    return d / 0x100000000;
  };
}

const index = (x, y) => y * WIDTH + x;
const inside = (x, y) => x >= 0 && y >= 0 && x < WIDTH && y < HEIGHT;

/**
 * Carve a perfect maze by depth-first search.
 *
 * Every cell starts walled in; the walk knocks out exactly one wall per cell it reaches, so the
 * result is a spanning tree — connected, and with no cycles. That guarantees the exit is always
 * reachable, which matters when someone is paying by the step to look for it.
 */
export function generate(gameId) {
  const random = seededRandom(gameId);
  const cells = new Array(WIDTH * HEIGHT).fill(0);
  const seen = new Array(WIDTH * HEIGHT).fill(false);
  const stack = [[0, 0]];
  seen[0] = true;

  while (stack.length > 0) {
    const [x, y] = stack[stack.length - 1];
    const options = [N, S, E, W].filter((dir) => {
      const [dx, dy] = STEP[dir];
      return inside(x + dx, y + dy) && !seen[index(x + dx, y + dy)];
    });
    if (options.length === 0) {
      stack.pop();
      continue;
    }
    const dir = options[Math.floor(random() * options.length)];
    const [dx, dy] = STEP[dir];
    cells[index(x, y)] |= dir;
    cells[index(x + dx, y + dy)] |= OPPOSITE[dir];
    seen[index(x + dx, y + dy)] = true;
    stack.push([x + dx, y + dy]);
  }
  return cells;
}

export const START = { x: 0, y: 0 };
export const EXIT = { x: WIDTH - 1, y: HEIGHT - 1 };

export function exits(cells, x, y) {
  const open = cells[index(x, y)];
  return Object.entries(DIRECTIONS)
    .filter(([, bit]) => (open & bit) !== 0)
    .map(([name]) => name);
}

export function canMove(cells, x, y, direction) {
  const bit = DIRECTIONS[direction];
  return bit !== undefined && (cells[index(x, y)] & bit) !== 0;
}

export function moved(x, y, direction) {
  const [dx, dy] = STEP[DIRECTIONS[direction]];
  return { x: x + dx, y: y + dy };
}

export const atExit = (x, y) => x === EXIT.x && y === EXIT.y;

/**
 * The shortest route from a cell to the exit.
 *
 * Used for two honest purposes and no dishonest one: pricing the map against what it saves, and
 * telling a finished run how close to optimal it was. It is never revealed by an endpoint that
 * has not been paid for.
 */
export function shortestPath(cells, from = START) {
  const previous = new Map();
  const queue = [from];
  const key = (p) => `${p.x},${p.y}`;
  const visited = new Set([key(from)]);

  while (queue.length > 0) {
    const at = queue.shift();
    if (atExit(at.x, at.y)) break;
    for (const direction of exits(cells, at.x, at.y)) {
      const next = moved(at.x, at.y, direction);
      if (visited.has(key(next))) continue;
      visited.add(key(next));
      previous.set(key(next), { from: at, direction });
      queue.push(next);
    }
  }

  const route = [];
  let cursor = EXIT;
  while (key(cursor) !== key(from)) {
    const step = previous.get(key(cursor));
    if (!step) return null;
    route.unshift(step.direction);
    cursor = step.from;
  }
  return route;
}

/**
 * The maze drawn for a person rather than a machine.
 *
 * The map endpoint sells this. It is also what a spectator sees at the end of a run, which is why
 * it marks where the agent is: a demo that shows a maze without showing the agent in it is a
 * picture, not a story.
 */
export function render(cells, at) {
  const lines = ["┌" + "───┬".repeat(WIDTH - 1) + "───┐"];
  for (let y = 0; y < HEIGHT; y++) {
    let middle = "│";
    let below = y === HEIGHT - 1 ? "└" : "├";
    for (let x = 0; x < WIDTH; x++) {
      const here = at && at.x === x && at.y === y;
      middle += here ? " ◆ " : atExit(x, y) ? " ★ " : "   ";
      middle += (cells[index(x, y)] & E) !== 0 ? " " : "│";
      if (y === HEIGHT - 1) {
        below += "───" + (x === WIDTH - 1 ? "┘" : "┴");
      } else {
        below += ((cells[index(x, y)] & S) !== 0 ? "   " : "───");
        below += x === WIDTH - 1 ? (y === HEIGHT - 1 ? "┘" : "┤") : "┼";
      }
    }
    lines.push(middle, below);
  }
  return lines.join("\n");
}
